version: '3.7'

services:
  web-client:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: vue-attendance
    network_mode: bridge
    volumes:
      - /app/
      - /app/node_modules
    labels:
      - vue-attendance
    stdin_open: true
    tty: true
    ports:
      - 3000:3000 

